### PR TITLE
3 Lines added

### PR DESCRIPTION
**Pull request by HackerXeroid**
Yo just shorted the unecessary commits into one commit. Update the repo accordingly.

### CODE REVIEW

**Comment by mexeroid** [comment]
Seems that! I will let the maintainers know first

**Comment by HackerXeroid** [comment]
Ok, as you wish!

**Comment by mexeroid** [comment]
Fine, the maintainers agreed they are asking for one more commit on the main branch

**Comment by HackerXeroid** [comment]
Ok, I will commit one more change.

**Pull request merged**
